base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

dvzo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('train_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("shifts/", include("shifts.urls")),
]

train_management/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),
    path("frequency-chart/", views.FrequencyChartData.as_view(), name="frequency-chart"),
    path("calendar/", views.Calendar.as_view(), name="calendar"),
    path("calendar/event_data", views.CalendarAvailabilityData.as_view(), name="event-data"),
    path("calendar/resource_data", views.CalendarResourceData.as_view(), name="resource-data"),
    path("dayplanning/", views.DayPlanningListView.as_view(), name="day-planning-list"),
    path("dayplanning/detail/<int:pk>/", views.DayPlanningDetailView.as_view(), name="day-planning-detail"),
    path(
        "dayplanning/detail/<int:pk>/recipients",
        views.DayPlanningRecipientView.as_view(),
        name="day-planning-recipients",
    ),
    path("dayplanning/update/<int:pk>/", views.DayPlanningUpdateView.as_view(), name="day-planning-update"),
    path("dayplanning/add/", views.DayPlanningCreateView.as_view(), name="day-planning-create"),
    path("dayplanning/<int:pk>/delete/", views.DayPlanningDeleteView.as_view(), name="day-planning-delete"),
    path("dayplanning/text/add/<int:pk>/", views.DayPlanningTextCreateView.as_view(), name="day-planning-text-create"),
    path("dayplanning/text/<int:pk>/", views.DayPlanningTextUpdateView.as_view(), name="day-planning-text-update"),
    path(
        "dayplanning/text/delete/<int:pk>/", views.DayPlanningTextDeleteView.as_view(), name="day-planning-text-delete"
    ),
    path(
        "dayplanning/<int:pk>/briefing/",
        views.BriefingPrintView.as_view(template_name="pdf/briefing.html"),
        name="briefing-pdf",
    ),
    path("bulletin/", views.BulletinPrintView.as_view(template_name="pdf/bulletin.html"), name="bulletin-pdf"),
    path(
        "bulletin-html/",
        views.DayPlanningBulletinView.as_view(template_name="pdf/bulletin_html.html"),
        name="bulletin-html",
    ),
    path("personnel/", views.PersonnelListView.as_view(), name="personnel-list"),
    path("personnel/<int:pk>/", views.PersonnelDetailView.as_view(), name="personnel-detail"),
    path("personnel/<int:pk>/edit", views.PersonnelUpdateView.as_view(), name="personnel-update"),
    path("personnel/add/", views.PersonnelCreateView.as_view(), name="personnel-create"),
    path("personnel/<int:pk>/delete/", views.PersonnelDeleteView.as_view(), name="personnel-delete"),
    path("function/", views.FunctionListView.as_view(), name="function-list"),
    path("function/<int:pk>/", views.FunctionUpdateView.as_view(), name="function-detail"),
    path("function/add/", views.FunctionCreateView.as_view(), name="function-create"),
    path("function/<int:pk>/delete/", views.FunctionDeleteView.as_view(), name="function-delete"),
    path("traincomposition/<int:pk>/", views.TrainCompositionUpdateView.as_view(), name="train-composition-update"),
    path("traincomposition/add/<int:pk>/", views.TrainCompositionCreateView.as_view(), name="train-composition-create"),
    path("carriage/", views.CarriageListView.as_view(), name="carriage-list"),
    path("carriage/<int:pk>/", views.CarriageDetailView.as_view(), name="carriage-detail"),
    path("carriage/<int:pk>/update/", views.CarriageUpdateView.as_view(), name="carriage-update"),
    path("carriage/add/", views.CarriageCreateView.as_view(), name="carriage-create"),
    path("carriage/<int:pk>/delete/", views.CarriageDeleteView.as_view(), name="carriage-delete"),
    path("engine/", views.EngineListView.as_view(), name="engine-list"),
    path("engine/<int:pk>/", views.EngineDetailView.as_view(), name="engine-detail"),
    path("engine/<int:pk>/update", views.EngineUpdateView.as_view(), name="engine-update"),
    path("engine/add/", views.EngineCreateView.as_view(), name="engine-create"),
    path("engine/<int:pk>/delete/", views.EngineDeleteView.as_view(), name="engine-delete"),
    path("phone/", views.PhoneNumberListView.as_view(), name="phone-list"),
    path("phone/<int:pk>/", views.PhoneNumberUpdateView.as_view(), name="phone-detail"),
    path("phone/add/", views.PhoneNumberCreateView.as_view(), name="phone-create"),
    path("phone/<int:pk>/delete/", views.PhoneNumberDeleteView.as_view(), name="phone-delete"),
    path("phonenumber/", views.PhoneNumberOverview.as_view(), name="phonenumber-list"),
    path("phonenumber/member/", views.PhoneNumberMemberList.as_view(), name="phonenumber-member-detail"),
    path("phonenumber/type/", views.PhoneNumberDetail.as_view(), name="phonenumber-detail"),
    path("station/", views.StationListView.as_view(), name="station-list"),
    path("station/<int:pk>/", views.StationUpdateView.as_view(), name="station-detail"),
    path("station/add/", views.StationCreateView.as_view(), name="station-create"),
    path("station/<int:pk>/delete/", views.StationDeleteView.as_view(), name="station-delete"),
    path(
        "dayplanning/train/reservation/add/<int:pk>/", views.ReservationCreateView.as_view(), name="reservation-create"
    ),
    path("dayplanning/train/reservation/<int:pk>/", views.ReservationUpdateView.as_view(), name="reservation-update"),
    path("dayplanning/train/reservation/", views.ReservationListView.as_view(), name="reservation-list"),
    path(
        "dayplanning/train/reservation/delete/<int:pk>/",
        views.ReservationDeleteView.as_view(),
        name="reservation-delete",
    ),
    path(
        "dayplanning/train/timetable/add/<int:pk>/",
        views.TrainTimetableCreateView.as_view(),
        name="train-timetable-create",
    ),
    path(
        "dayplanning/train/timetable/<int:pk>/", views.TrainTimetableUpdateView.as_view(), name="train-timetable-update"
    ),
    path(
        "dayplanning/train/timetable/delete/<int:pk>/",
        views.TrainTimetableDeleteView.as_view(),
        name="train-timetable-delete",
    ),
    path(
        "traintimetabletemplate/", views.TrainTimetableTemplateListView.as_view(), name="train-timetable-template-list"
    ),
    path(
        "traintimetabletemplate/choose/",
        views.ChooseTimetableTemplatesView.as_view(),
        name="train-timetable-template-choose",
    ),
    path(
        "traintimetabletemplate/use/",
        views.CreateTimetablesFromTemplateView.as_view(),
        name="train-timetable-template-use",
    ),
    path(
        "traintimetabletemplate/<int:pk>/",
        views.TrainTimetableTemplateUpdateView.as_view(),
        name="train-timetable-template-detail",
    ),
    path(
        "traintimetabletemplate/add/",
        views.TrainTimetableTemplateCreateView.as_view(),
        name="train-timetable-template-create",
    ),
    path(
        "traintimetabletemplate/<int:pk>/delete/",
        views.TrainTimetableTemplateDeleteView.as_view(),
        name="train-timetable-template-delete",
    ),
    path("edit-train-functions/<int:train_id>", views.EditTrainFunctions.as_view(), name="edit-train-functions"),
    path(
        "edit-dayplanning-functions/<int:dayplanning_id>",
        views.EditDayPlanningFunctions.as_view(),
        name="edit-dayplanning-functions",
    ),
    path("traincomposition/add/<int:pk>/", views.TrainCompositionCreateView.as_view(), name="train-composition-create"),
    path("traincomposition/delete/<int:pk>/", views.TrainDeleteView.as_view(), name="train-composition-delete"),
    path("availability/", views.AvailabilityListView.as_view(), name="availability-list"),
    path(
        "availability/engine/<int:pk>/", views.AvailabilityEngineUpdateView.as_view(), name="availability-engine-detail"
    ),
    path(
        "availability/carriage/<int:pk>/",
        views.AvailabilityCarriageUpdateView.as_view(),
        name="availability-carriage-detail",
    ),
    path(
        "availability/engine/add/<int:pk>",
        views.AvailabilityEngineCreateView.as_view(),
        name="availability-engine-create",
    ),
    path(
        "availability/carriage/add/<int:pk>",
        views.AvailabilityCarriageCreateView.as_view(),
        name="availability-carriage-create",
    ),
    path("availability/<int:pk>/delete/", views.AvailabilityDeleteView.as_view(), name="availability-delete"),
    path("reservation-calendar/", views.ReservationCalendar.as_view(), name="reservation-calendar"),
    path(
        "reservation-calendar/<int:pk>", views.ReservationCalendarTrains.as_view(), name="reservation-calendar-trains"
    ),
    path("reservation-calendar-data/", views.ReservationCalendarData.as_view(), name="reservation-calendar-data"),
    path("copy-recipient/", views.CopyRecipientListView.as_view(), name="copy-recipient-list"),
    path(
        "copy-recipient/table",
        views.CopyRecipientListView.as_view(template_name="train_management/copyrecipient_table.html"),
        name="copy-recipient-table",
    ),
    path("copy-recipient/<int:pk>/", views.CopyRecipientUpdateView.as_view(), name="copy-recipient-detail"),
    path("copy-recipient/add/", views.CopyRecipientCreateView.as_view(), name="copy-recipient-create"),
    path("copy-recipient/<int:pk>/delete/", views.CopyRecipientDeleteView.as_view(), name="copy-recipient-delete"),
    path("personnel-category/", views.PersonnelCategoryListView.as_view(), name="personnel-category-list"),
    path("personnel-category/<int:pk>/", views.PersonnelCategoryUpdateView.as_view(), name="personnel-category-detail"),
    path("personnel-category/add/", views.PersonnelCategoryCreateView.as_view(), name="personnel-category-create"),
    path(
        "personnel-category/<int:pk>/delete/",
        views.PersonnelCategoryDeleteView.as_view(),
        name="personnel-category-delete",
    ),
]

train_management/models/dayplanning.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel
from train_management.models import FunctionPersons


class DayPlanning(AbstractDvzoModel):
    class Meta:
        verbose_name = _("dayplanning.singular")
        verbose_name_plural = _("dayplanning.plural")

    class DayPlanningStatus(models.TextChoices):
        DRAFT = "draft", _("dayplanning.status.draft")
        CONFIRMED = "confirmed", _("dayplanning.status.confirmed")
        EXECUTED = "executed", _("dayplanning.status.executed")

    class DayPlanningType(models.TextChoices):
        SUNDAY = "sunday", _("dayplanning.type.sunday")
        EXTRA = "extra", _("dayplanning.type.extra")
        OTHER = "other", _("dayplanning.type.other")

    class DayPlanningBilled(models.TextChoices):
        YES = "yes", _("dayplanning.billed.yes")
        NO = "no", _("dayplanning.billed.no")
        NOT_APPLICABLE = "not_applicable", _("dayplanning.billed.not_applicable")

    class DayPlanningSlot(models.TextChoices):
        OPEN = "open", _("dayplanning.slot.open")
        ORDERED = "ordered", _("dayplanning.slot.ordered")
        RESERVED = "reserved", _("dayplanning.slot.reserved")
        RECEIVED = "received", _("dayplanning.slot.received")
        NOT_APPLICABLE = "not_applicable", _("dayplanning.slot.not_applicable")

    class DayPlanningPersonnelDisposition(models.TextChoices):
        OPEN = "open", _("dayplanning.personnel_disposition.open")
        DISPOSED = "disposed", _("dayplanning.personnel_disposition.disposed")
        NOT_APPLICABLE = "not_applicable", _("dayplanning.personnel_disposition.not_applicable")

    class DayPlanningBookingStatus(models.TextChoices):
        PROPOSAL = "proposal", _("dayplanning.booking_status.proposal")
        RESERVATION = "reservation", _("dayplanning.booking_status.reservation")
        BOOKED = "booked", _("dayplanning.booking_status.booked")
        CANCELLED_DVZO = "cancelled_dvzo", _("dayplanning.booking_status.cancelled_dvzo")
        CANCELLED_CUSTOMER = "cancelled_customer", _("dayplanning.booking_status.cancelled_customer")
        NOT_APPLICABLE = "not_applicable", _("dayplanning.booking_status.not_applicable")

    class DayPlanningEnginePlanningStatus(models.TextChoices):
        OPEN = "open", _("dayplanning.vehicle_planning_status.open")
        ASKED = "asked", _("dayplanning.vehicle_planning_status.asked")
        OK = "ok", _("dayplanning.vehicle_planning_status.ok")

    class DayPlanningCarriagePlanningStatus(models.TextChoices):
        OPEN = "open", _("dayplanning.vehicle_planning_status.open")
        ASKED = "asked", _("dayplanning.vehicle_planning_status.asked")
        OK = "ok", _("dayplanning.vehicle_planning_status.ok")

    class DayPlanningRailwayCompany(models.TextChoices):
        TR = "tr", _("dayplanning.railway_company.tr")
        SBB = "sbb", _("dayplanning.railway_company.sbb")
        OTHER = "other", _("dayplanning.railway_company.other")

    label = models.CharField(_("dayplanning.label"), max_length=200)
    day_planning_type = models.CharField(
        _("dayplanning.day_planning_type"), max_length=80, choices=DayPlanningType.choices
    )
    date = models.DateField(_("dayplanning.date"))
    status = models.CharField(_("dayplanning.status"), max_length=80, choices=DayPlanningStatus.choices)
    billed = models.TextField(
        _("dayplanning.billed"),
        max_length=80,
        choices=DayPlanningBilled.choices,
        default=DayPlanningBilled.NOT_APPLICABLE,
    )
    function_persons = models.ManyToManyField(FunctionPersons, related_name="dayplanning")
    slot_ordered_st = models.CharField(
        _("dayplanning.slot_ordered_st"),
        max_length=80,
        choices=DayPlanningSlot.choices,
        default=DayPlanningSlot.NOT_APPLICABLE,
    )
    slot_ordered_sbb = models.CharField(
        _("dayplanning.slot_ordered_sbb"),
        max_length=80,
        choices=DayPlanningSlot.choices,
        default=DayPlanningSlot.NOT_APPLICABLE,
    )
    personnel_disposition = models.CharField(
        _("dayplanning.personnel_disposition"),
        max_length=80,
        choices=DayPlanningPersonnelDisposition.choices,
        default=DayPlanningPersonnelDisposition.OPEN,
    )
    customers = models.IntegerField(_("dayplanning.customers"), blank=True, null=True)
    price = models.DecimalField(_("dayplanning.price"), blank=True, max_digits=8, decimal_places=2, null=True)
    booking_status = models.CharField(
        _("dayplanning.booking_status"),
        max_length=80,
        choices=DayPlanningBookingStatus.choices,
        default=DayPlanningBookingStatus.NOT_APPLICABLE,
    )
    comment = models.TextField(_("dayplanning.comment"), blank=True)
    post_mortem = models.TextField(_("dayplanning.post_mortem"), blank=True)
    engine_planning_status = models.CharField(
        _("dayplanning.engine_planning_status"),
        max_length=80,
        choices=DayPlanningEnginePlanningStatus.choices,
        default=DayPlanningEnginePlanningStatus.OPEN,
    )
    carriage_planning_status = models.CharField(
        _("dayplanning.carriage_planning_status"),
        max_length=80,
        choices=DayPlanningCarriagePlanningStatus.choices,
        default=DayPlanningCarriagePlanningStatus.OPEN,
    )
    railway_company = models.CharField(
        _("dayplanning.railway_company"),
        max_length=80,
        choices=DayPlanningRailwayCompany.choices,
        default=DayPlanningRailwayCompany.TR,
    )

    def __str__(self):
        return self.label


class DayPlanningText(AbstractDvzoModel):
    class Meta:
        verbose_name = _("dayplanning_text.singular")
        verbose_name_plural = _("dayplanning_text.plural")

    label = models.CharField(_("dayplanning_text.label"), max_length=200)
    text = models.TextField(_("dayplanning_text.text"))
    sorting = models.IntegerField(_("dayplanning_text.sorting"), blank=True, null=True)
    dayplanning = models.ForeignKey(DayPlanning, on_delete=models.CASCADE)

    def __str__(self):
        return self.label

train_management/forms/availability.py
from django import forms
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from train_management.models import Availability


class AvailabilityForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = "mb-3"

    class Meta:
        model = Availability
        fields = ["availability_status", "start", "end"]

    start = forms.DateField(widget=forms.DateInput(format="%Y-%m-%d"))
    end = forms.DateField(widget=forms.DateInput(format="%Y-%m-%d"))

train_management/forms/copy_recipient.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from train_management.models import CopyRecipient


class CopyRecipientForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = "mb-3"

    class Meta:
        model = CopyRecipient
        fields = ["label", "email"]

train_management/forms/dayplanning_text.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from train_management.models import DayPlanningText


class DayPlanningTextForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = "mb-3"

    class Meta:
        model = DayPlanningText
        fields = ["label", "text"]

    def __init__(self, *args, **kwargs):
        super(DayPlanningTextForm, self).__init__(*args, **kwargs)

        self.fields["text"].widget.attrs["class"] = "tinymce-textarea"

train_management/templates/pdf/briefing.html
{% extends "base_pdf.html" %}
{% load i18n %}

{% block title %}{% translate "template.dayplanning.detail.title" %} - {{ object.label }}{% endblock %}

{% block content %}
<h1>Briefing {{object.label}} - {{object.date}}</h1>

<!-- Textblöcke -->
{% for dayplanning_text in dayplanning_texts %}
{% autoescape off %}
<p>
  {{dayplanning_text.text}}
</p>
{% endautoescape %}
{% endfor %}


<!-- Zugformation -->
<h3>Zugformation</h3>
<table class="table table-sm">
  <thead class="table-dark">
  {% for train_data in trains_data %}
  {% with train=train_data.train %}
  <th>{{train}}</th>
  {% endwith %}
  {% empty %}
  {% endfor %}
  </thead>
  <tbody>
  <tr>
    {% for train_data in trains_data %}
    {% with train=train_data.train %}
    <td>
      {% for vehicle in train.vehicles %}
      {% if vehicle.vehicle_type == "engine" %}
      <span class="badge bg-primary">{{ vehicle.label }}</span>
      {% elif vehicle.vehicle_type == "carriage" %}
      {% if vehicle.carriage_type == "seat" %}
      <span class="badge bg-success">{{ vehicle.label }}</span>
      {% elif vehicle.carriage_type == "gastro" %}
      <span class="badge bg-danger">{{ vehicle.label }}</span>
      {% elif vehicle.carriage_type == "amor" %}
      <span class="badge bg-warning">{{ vehicle.label }}</span>
      {% elif vehicle.carriage_type == "luggage" %}
      <span class="badge bg-secondary">{{ vehicle.label }}</span>
      {% else %}
      <span class="badge bg-dark">{{ vehicle.label }}</span>
      {% endif %}
      {% else %}
      peter
      {% endif %}<br>
      {% endfor %}
    </td>
    {% endwith %}
    {% empty %}
    {% endfor %}
  </tr>
  </tbody>
</table>

<!-- Personal -->

<h3>Personal</h3>
<table class="table table-sm">
  <thead class="table-dark">
  <th>Einsatzort</th>
  <th>Funktion</th>
  <th>Name</th>
  <th>Telefon</th>
  </thead>
  <tbody>
  {% for train_data in trains_data %}
  {% with train=train_data.train %}
  <tr>
    <td rowspan="{{train_data.functions.items|length}}">{{train}}</td>
    {% for function, persons in train_data.functions.items %}
    <td>{{function}}</td>
    <td>
      {% for person in persons %}
      {{ person }}
      {% if not forloop.last %}<br>{% endif %}
      {% endfor %}
    </td>
    <td>
      {% for person in persons %}
      {% if person.mobile_phone_public == "yes" %}
      {{person.mobile_phone.as_national}}
      {% endif %}
      {% if not forloop.last %}<br>{% endif %}
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
  {% endwith %}
  {% empty %}
  {% endfor %}

  {% for function_type, functions in dayplanning_functions.items %}
  <tr>
    <td rowspan="{{functions.items|length}}">{{function_type}}</td>
    {% for function, persons in functions.items %}
    <td>{{function}}</td>
    <td>
      {% for person in persons %}
      {{person}}
      {% if not forloop.last %}<br>{% endif %}
      {% endfor %}
    </td>
    <td>
      {% for person in persons %}
      {% if person.mobile_phone_public == "yes" %}
      {{person.mobile_phone.as_national}}
      {% endif %}
      {% if not forloop.last %}<br>{% endif %}
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
  {% endfor %}
  </tbody>
</table>


<!-- Reservationen -->
<h3>Reservationen</h3>
<table class="table table-sm dvzo-25">
  <thead class="table-dark">
  <th>Fahrt</th>
  <th>Von - bis</th>
  <th>PAX</th>
  <th>Kontakt</th>
  <th>Bemerkungen</th>
  </thead>
  <tbody>
  {% for traintimetable in traintimetables %}
  {% with reservations=traintimetable.reservation_set.all %}
  {% if reservations|length > 0 %}
  <tr>
    <td rowspan={{reservations|length}}>
      <div class="badge bg-secondary">
        {{ traintimetable.label }}
      </div>
      <span class="fw-bold">{{ traintimetable.start_station.label_short }}</span>
      <span>{{ traintimetable.start_time }}</span>
      - <span class="fw-bold">{{ traintimetable.destination_station.label_short }}</span>
      <span>{{ traintimetable.destination_time }}</span>
    </td>
    {% endif %}
    {% for reservation in reservations %}
    <td>
      <span class="fw-bold">{{reservation.start.label_short}}</span>
                  - <span class="fw-bold">{{reservation.end.label_short}}</span>
    </td>
    <td>{{reservation.amount}}</td>
    <td>{{reservation.label}} ({{reservation.phone.as_national}})</td>
    <td>{{reservation.comment}}</td>
  </tr>
  {% endfor %}
  {% endwith %}
  {% endfor %}
  </tbody>
</table>

{% endblock content %}

train_management/templates/pdf/bulletin.html
{% extends "base_pdf.html" %}
{% load i18n %}

{% block title %}{% translate "template.dayplanning.detail.title" %} - {{ object.label }}{% endblock %}

{% block style %}
<style>
  @page {
    size: landscape;

    @top-right {
      color: #a9a;
      content: '{% now "SHORT_DATETIME_FORMAT" %}';
      font-family: 'Inter var', sans-serif;
      font-size: 9pt;
    }
  }
</style>

{% endblock %}


{% block content %}
<h1>Bulletin</h1>

{% for day_planning in day_plannings %}
<div style="page-break-inside: avoid">
  <b>{{day_planning.date}} {{day_planning}}</b>
  <table class="table table-sm table-bulletin">
    <thead class="table-dark">
    <th style="width: 5cm;">Buchung</th>
    <th>Fahrten</th>
    <th style="width: 10cm;">Bemerkungen</th>
    </thead>
    <tbody>
    <tr>
      <td>
        <table>
          <tr>
            <td>Buchungsstatus:</td>
            <td>{{day_planning.get_booking_status_display}}</td>
          </tr>
          <tr>
            <td>PAX:</td>
            <td>{{day_planning.customers}}</td>
          </tr>
        </table>
      </td>
      <td>
        <table>
          {% for train in day_planning.train_set.all %}
          <tr>
            <td>
              {{train}}
            </td>
            <td>
              {% for vehicle in train.vehicles %}
              {% if vehicle.vehicle_type == "engine" %}
              <span class="badge bg-primary">{{ vehicle.label }}</span>
              {% elif vehicle.vehicle_type == "carriage" %}
              {% if vehicle.carriage_type == "seat" %}
              <span class="badge bg-success">{{ vehicle.label }}</span>
              {% elif vehicle.carriage_type == "gastro" %}
              <span class="badge bg-danger">{{ vehicle.label }}</span>
              {% elif vehicle.carriage_type == "amor" %}
              <span class="badge bg-warning">{{ vehicle.label }}</span>
              {% elif vehicle.carriage_type == "luggage" %}
              <span class="badge bg-secondary">{{ vehicle.label }}</span>
              {% else %}
              <span class="badge bg-dark">{{ vehicle.label }}</span>
              {% endif %}
              {% else %}
              peter
              {% endif %}
              {% endfor %}
            </td>
          </tr>
          {% for timetable in train.traintimetable_set.all %}
          <tr>
            <td>
              <div class="badge bg-secondary">
                {{ timetable.label }}
              </div>
            </td>
            <td>
              <span class="fw-bold">{{ timetable.start_station }}</span>
              <span>{{ timetable.start_time }}</span>
              - <span class="fw-bold">{{ timetable.destination_station }}</span>
              <span>{{ timetable.destination_time }}</span>
            </td>
          </tr>
          {% endfor %}
          {% endfor %}
        </table>
      </td>
      <td>{{ day_planning.comment }}</td>
    </tr>
    </tbody>
  </table>
</div>


{% endfor %}

{% endblock content %}