base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

dvzo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('train_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("shifts/", include("shifts.urls")),
]

train_management/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),
    path("frequency-chart/", views.FrequencyChartData.as_view(), name="frequency-chart"),
    path("calendar/", views.Calendar.as_view(), name="calendar"),
    path("calendar/event_data", views.CalendarAvailabilityData.as_view(), name="event-data"),
    path("calendar/resource_data", views.CalendarResourceData.as_view(), name="resource-data"),
    path("dayplanning/", views.DayPlanningListView.as_view(), name="day-planning-list"),
    path("dayplanning/detail/<int:pk>/", views.DayPlanningDetailView.as_view(), name="day-planning-detail"),
    path(
        "dayplanning/detail/<int:pk>/recipients",
        views.DayPlanningRecipientView.as_view(),
        name="day-planning-recipients",
    ),
    path("dayplanning/update/<int:pk>/", views.DayPlanningUpdateView.as_view(), name="day-planning-update"),
    path("dayplanning/add/", views.DayPlanningCreateView.as_view(), name="day-planning-create"),
    path("dayplanning/<int:pk>/delete/", views.DayPlanningDeleteView.as_view(), name="day-planning-delete"),
    path("dayplanning/text/add/<int:pk>/", views.DayPlanningTextCreateView.as_view(), name="day-planning-text-create"),
    path("dayplanning/text/<int:pk>/", views.DayPlanningTextUpdateView.as_view(), name="day-planning-text-update"),
    path(
        "dayplanning/text/delete/<int:pk>/", views.DayPlanningTextDeleteView.as_view(), name="day-planning-text-delete"
    ),
    path(
        "dayplanning/<int:pk>/briefing/",
        views.BriefingPrintView.as_view(template_name="pdf/briefing.html"),
        name="briefing-pdf",
    ),
    path("bulletin/", views.BulletinPrintView.as_view(template_name="pdf/bulletin.html"), name="bulletin-pdf"),
    path(
        "bulletin-html/",
        views.DayPlanningBulletinView.as_view(template_name="pdf/bulletin_html.html"),
        name="bulletin-html",
    ),
    path("personnel/", views.PersonnelListView.as_view(), name="personnel-list"),
    path("personnel/<int:pk>/", views.PersonnelDetailView.as_view(), name="personnel-detail"),
    path("personnel/<int:pk>/edit", views.PersonnelUpdateView.as_view(), name="personnel-update"),
    path("personnel/add/", views.PersonnelCreateView.as_view(), name="personnel-create"),
    path("personnel/<int:pk>/delete/", views.PersonnelDeleteView.as_view(), name="personnel-delete"),
    path("function/", views.FunctionListView.as_view(), name="function-list"),
    path("function/<int:pk>/", views.FunctionUpdateView.as_view(), name="function-detail"),
    path("function/add/", views.FunctionCreateView.as_view(), name="function-create"),
    path("function/<int:pk>/delete/", views.FunctionDeleteView.as_view(), name="function-delete"),
    path("traincomposition/<int:pk>/", views.TrainCompositionUpdateView.as_view(), name="train-composition-update"),
    path("traincomposition/add/<int:pk>/", views.TrainCompositionCreateView.as_view(), name="train-composition-create"),
    path("carriage/", views.CarriageListView.as_view(), name="carriage-list"),
    path("carriage/<int:pk>/", views.CarriageDetailView.as_view(), name="carriage-detail"),
    path("carriage/<int:pk>/update/", views.CarriageUpdateView.as_view(), name="carriage-update"),
    path("carriage/add/", views.CarriageCreateView.as_view(), name="carriage-create"),
    path("carriage/<int:pk>/delete/", views.CarriageDeleteView.as_view(), name="carriage-delete"),
    path("engine/", views.EngineListView.as_view(), name="engine-list"),
    path("engine/<int:pk>/", views.EngineDetailView.as_view(), name="engine-detail"),
    path("engine/<int:pk>/update", views.EngineUpdateView.as_view(), name="engine-update"),
    path("engine/add/", views.EngineCreateView.as_view(), name="engine-create"),
    path("engine/<int:pk>/delete/", views.EngineDeleteView.as_view(), name="engine-delete"),
    path("phone/", views.PhoneNumberListView.as_view(), name="phone-list"),
    path("phone/<int:pk>/", views.PhoneNumberUpdateView.as_view(), name="phone-detail"),
    path("phone/add/", views.PhoneNumberCreateView.as_view(), name="phone-create"),
    path("phone/<int:pk>/delete/", views.PhoneNumberDeleteView.as_view(), name="phone-delete"),
    path("phonenumber/", views.PhoneNumberOverview.as_view(), name="phonenumber-list"),
    path("phonenumber/member/", views.PhoneNumberMemberList.as_view(), name="phonenumber-member-detail"),
    path("phonenumber/type/", views.PhoneNumberDetail.as_view(), name="phonenumber-detail"),
    path("station/", views.StationListView.as_view(), name="station-list"),
    path("station/<int:pk>/", views.StationUpdateView.as_view(), name="station-detail"),
    path("station/add/", views.StationCreateView.as_view(), name="station-create"),
    path("station/<int:pk>/delete/", views.StationDeleteView.as_view(), name="station-delete"),
    path(
        "dayplanning/train/reservation/add/<int:pk>/", views.ReservationCreateView.as_view(), name="reservation-create"
    ),
    path("dayplanning/train/reservation/<int:pk>/", views.ReservationUpdateView.as_view(), name="reservation-update"),
    path("dayplanning/train/reservation/", views.ReservationListView.as_view(), name="reservation-list"),
    path(
        "dayplanning/train/reservation/delete/<int:pk>/",
        views.ReservationDeleteView.as_view(),
        name="reservation-delete",
    ),
    path(
        "dayplanning/train/timetable/add/<int:pk>/",
        views.TrainTimetableCreateView.as_view(),
        name="train-timetable-create",
    ),
    path(
        "dayplanning/train/timetable/<int:pk>/", views.TrainTimetableUpdateView.as_view(), name="train-timetable-update"
    ),
    path(
        "dayplanning/train/timetable/delete/<int:pk>/",
        views.TrainTimetableDeleteView.as_view(),
        name="train-timetable-delete",
    ),
    path(
        "traintimetabletemplate/", views.TrainTimetableTemplateListView.as_view(), name="train-timetable-template-list"
    ),
    path(
        "traintimetabletemplate/choose/",
        views.ChooseTimetableTemplatesView.as_view(),
        name="train-timetable-template-choose",
    ),
    path(
        "traintimetabletemplate/use/",
        views.CreateTimetablesFromTemplateView.as_view(),
        name="train-timetable-template-use",
    ),
    path(
        "traintimetabletemplate/<int:pk>/",
        views.TrainTimetableTemplateUpdateView.as_view(),
        name="train-timetable-template-detail",
    ),
    path(
        "traintimetabletemplate/add/",
        views.TrainTimetableTemplateCreateView.as_view(),
        name="train-timetable-template-create",
    ),
    path(
        "traintimetabletemplate/<int:pk>/delete/",
        views.TrainTimetableTemplateDeleteView.as_view(),
        name="train-timetable-template-delete",
    ),
    path("edit-train-functions/<int:train_id>", views.EditTrainFunctions.as_view(), name="edit-train-functions"),
    path(
        "edit-dayplanning-functions/<int:dayplanning_id>",
        views.EditDayPlanningFunctions.as_view(),
        name="edit-dayplanning-functions",
    ),
    path("traincomposition/add/<int:pk>/", views.TrainCompositionCreateView.as_view(), name="train-composition-create"),
    path("traincomposition/delete/<int:pk>/", views.TrainDeleteView.as_view(), name="train-composition-delete"),
    path("availability/", views.AvailabilityListView.as_view(), name="availability-list"),
    path(
        "availability/engine/<int:pk>/", views.AvailabilityEngineUpdateView.as_view(), name="availability-engine-detail"
    ),
    path(
        "availability/carriage/<int:pk>/",
        views.AvailabilityCarriageUpdateView.as_view(),
        name="availability-carriage-detail",
    ),
    path(
        "availability/engine/add/<int:pk>",
        views.AvailabilityEngineCreateView.as_view(),
        name="availability-engine-create",
    ),
    path(
        "availability/carriage/add/<int:pk>",
        views.AvailabilityCarriageCreateView.as_view(),
        name="availability-carriage-create",
    ),
    path("availability/<int:pk>/delete/", views.AvailabilityDeleteView.as_view(), name="availability-delete"),
    path("reservation-calendar/", views.ReservationCalendar.as_view(), name="reservation-calendar"),
    path(
        "reservation-calendar/<int:pk>", views.ReservationCalendarTrains.as_view(), name="reservation-calendar-trains"
    ),
    path("reservation-calendar-data/", views.ReservationCalendarData.as_view(), name="reservation-calendar-data"),
    path("copy-recipient/", views.CopyRecipientListView.as_view(), name="copy-recipient-list"),
    path(
        "copy-recipient/table",
        views.CopyRecipientListView.as_view(template_name="train_management/copyrecipient_table.html"),
        name="copy-recipient-table",
    ),
    path("copy-recipient/<int:pk>/", views.CopyRecipientUpdateView.as_view(), name="copy-recipient-detail"),
    path("copy-recipient/add/", views.CopyRecipientCreateView.as_view(), name="copy-recipient-create"),
    path("copy-recipient/<int:pk>/delete/", views.CopyRecipientDeleteView.as_view(), name="copy-recipient-delete"),
    path("personnel-category/", views.PersonnelCategoryListView.as_view(), name="personnel-category-list"),
    path("personnel-category/<int:pk>/", views.PersonnelCategoryUpdateView.as_view(), name="personnel-category-detail"),
    path("personnel-category/add/", views.PersonnelCategoryCreateView.as_view(), name="personnel-category-create"),
    path(
        "personnel-category/<int:pk>/delete/",
        views.PersonnelCategoryDeleteView.as_view(),
        name="personnel-category-delete",
    ),
]

train_management/models/availability.py
from django.db import models
from django.db.models.signals import post_delete
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel
from train_management.models import DayPlanning
from train_management.models import TrainConfiguration
from train_management.models import Vehicle


class Availability(AbstractDvzoModel):
    class Meta:
        verbose_name = _("availability.singular")
        verbose_name_plural = _("availability.plural")

    class AvailabilityStatus(models.TextChoices):
        IN_USE = "in_use", _("availability.availability_status.in_use")
        ASK = "ask", _("availability.availability_status.ask")
        SERVICE = "servicing", _("availability.availability_status.servicing")
        LOCKED = "locked", _("availability.availability_status.locked")

    vehicle = models.ForeignKey(Vehicle, on_delete=models.DO_NOTHING)
    dayplanning = models.ForeignKey(DayPlanning, on_delete=models.DO_NOTHING, null=True)
    start = models.DateField(_("availability.start"))
    end = models.DateField(_("availability.end"))
    availability_status = models.CharField(
        _("availability.status"), max_length=80, choices=AvailabilityStatus.choices, default=AvailabilityStatus.SERVICE
    )

    def __str__(self):
        return self.vehicle.label


@receiver(post_delete, sender=TrainConfiguration)
def train_configuration_post_delete(sender, instance, *args, **kwargs):
    day_planning = DayPlanning.objects.get(id=instance.train.day_planning.id)
    vehicle = Vehicle.objects.get(id=instance.vehicle.id)
    Availability.objects.filter(vehicle=vehicle, dayplanning=day_planning).delete()


@receiver(post_save, sender=TrainConfiguration)
def train_configuration_post_create(sender, instance, created, *args, **kwargs):
    day_planning = DayPlanning.objects.get(id=instance.train.day_planning.id)
    vehicle = Vehicle.objects.get(id=instance.vehicle.id)
    availability_status = Availability.AvailabilityStatus.IN_USE
    date = day_planning.date
    if created:
        Availability(
            vehicle=vehicle, dayplanning=day_planning, start=date, end=date, availability_status=availability_status
        ).save()

train_management/models/dvzofunction.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel
from train_management.models import PersonnelCategory


class DvzoFunction(AbstractDvzoModel):
    class Meta:
        verbose_name = _("dvzo_function.singular")
        verbose_name_plural = _("dvzo_function.plural")

    class FunctionType(models.TextChoices):
        TRAIN = "train", _("dvzo_function.function_type.train")
        BAUMA = "bauma", _("dvzo_function.function_type.bauma")
        NEUTHAL = "neuthal", _("dvzo_function.function_type.neuthal")
        BAERETSWIL = "baeretswil", _("dvzo_function.function_type.baeretswil")
        HINWIL = "hinwil", _("dvzo_function.function_type.hinwil")

    label = models.CharField(_("dvzo_function.label"), max_length=200)
    label_short = models.CharField(_("dvzo_function.label_short"), max_length=80)
    sorting = models.IntegerField(_("dvzo_function.sorting"), null=True, blank=True)
    function_type = models.CharField(_("dvzo_function.function_type"), max_length=80, choices=FunctionType.choices)
    category = models.ForeignKey(PersonnelCategory, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.label

train_management/models/personnel.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from train_management.models import AbstractDvzoModel
from train_management.models import PersonnelCategory


class Personnel(AbstractDvzoModel):
    class Meta:
        verbose_name = _("personnel.singular")
        verbose_name_plural = _("personnel.plural")

    class PersonnelStatus(models.TextChoices):
        ACTIVE = "active", _("personnel.personnel_status.active")
        INACTIVE = "inactive", _("personnel.personnel_status.inactive")

    class PersonnelMobilePublic(models.TextChoices):
        YES = "yes", _("personnel.personnel_mobile_public.yes")
        NO = "no", _("personnel.personnel_mobile_public.no")
        UNKNOWN = "unknown", _("personnel.personnel_mobile_public.unknown")

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    mobile_phone = PhoneNumberField(_("personnel.mobile_phone"), blank=True)
    status = models.CharField(_("personnel.status"), max_length=80, choices=PersonnelStatus.choices)
    mobile_phone_public = models.CharField(
        _("personnel.personnel_mobile_public"),
        max_length=80,
        choices=PersonnelMobilePublic.choices,
        default=PersonnelMobilePublic.UNKNOWN,
    )
    category = models.ManyToManyField(PersonnelCategory, blank=True)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    @property
    def username(self):
        return self.user.username

    @property
    def last_name(self):
        return self.user.last_name

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def email(self):
        return self.user.email

train_management/models/personnel_category.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel


class PersonnelCategory(AbstractDvzoModel):
    class Meta:
        verbose_name = _("personnel_category.singular")
        verbose_name_plural = _("personnel_category.plural")

    class PersonnelCategoryType(models.TextChoices):
        ENGINE = "engine", _("personnel_category.type.engine")
        TRAIN = "train", _("personnel_category.type.train")
        GASTRO = "gastro", _("personnel_category.type.gastro")
        STATION = "station", _("personnel_category.type.station")
        OTHER = "other", _("personnel_category.type.other")

    label = models.CharField(_("personnel_category.label"), max_length=200)
    type = models.CharField(_("personnel_category.type"), max_length=80, choices=PersonnelCategoryType.choices)

    def __str__(self):
        return self.label

train_management/models/phonenumber.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from train_management.models import AbstractDvzoModel


class PhoneNumber(AbstractDvzoModel):
    class Meta:
        verbose_name = _("phone_number.singular")
        verbose_name_plural = _("phone_number.plural")

    class PhoneNumberType(models.TextChoices):
        SBB = "sbb", _("phone_number.type.sbb")
        EMERGENCY = "emergency", _("phone_number.type.emergency")
        DVZO = "dvzo", _("phone_number.type.dvzo")
        OTHER = "other", _("phone_number.type.other")

    label = models.CharField(_("phone_number.label"), max_length=200)
    phone_number = PhoneNumberField(_("phone_number.phone_number"))
    phone_number_type = models.CharField(_("phone_number.type"), max_length=80, choices=PhoneNumberType.choices)

    def __str__(self):
        return self.label

train_management/forms/copy_recipient.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from train_management.models import CopyRecipient


class CopyRecipientForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = "mb-3"

    class Meta:
        model = CopyRecipient
        fields = ["label", "email"]

train_management/templates/train_management/engine_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "template.engine.list.title" %}{% endblock %}

{% block content %}
<div class="dvzo-container">
  <div class="dvzo-header">
    {% translate "template.engine.list.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <div class="card my-2">
          <div class="card-body">
            <div class="card-text">
              <table
                id="engineListTable"
                data-toggle="table"
                data-classes="table table-hover table-condensed"
                data-striped="true"
                data-locale="de-DE"
                data-search="true"
                data-sort-name="label"
                data-sort-order="asc"
                data-pagination="true"
                data-page-size="15"
                data-page-list="[15, 25, 50, 100, 200, All]"
              >
                <thead>
                <tr>
                  <th data-field="state" data-checkbox="true">{% translate "table.state" %}</th>
                  <th data-field="id" data-visible="false">{% translate "table.id" %}</th>
                  <th data-field="label" data-sortable="true">{% translate "vehicle.label" %}</th>
                  <th data-field="historic_name" data-sortable="true">{% translate "vehicle.historic_name" %}</th>
                  <th data-field="status" data-sortable="true">{% translate "vehicle.status" %}</th>
                  <th data-field="power_unit" data-sortable="false">{% translate "vehicle.power_unit" %}</th>
                  <th data-field="actions" data-sortable="false"></th>
                </tr>
                </thead>
                <tbody>
                {% for engine in engines %}
                <tr>
                  <td></td>
                  <td>{{ engine.id }}</td>
                  <td>{{ engine.label }}</td>
                  <td>{{ engine.historic_name }}</td>
                  <td>
                    {% if engine.status == "available" %}
                    <span class="badge bg-success">{{ engine.get_status_display }}</span>
                    {% else %}
                    {{ engine.get_status_display }}
                    {% endif %}
                  </td>
                  <td>{{ engine.get_power_unit_display }}</td>
                  <td>
                    {% if perms.train_management.delete_vehicle %}
                    <a href="{% url 'engine-delete' pk=engine.id %}">
                      <i class="fas fa-trash-alt text-danger"></i>
                    </a>
                    {% endif %}
                    <a href="{% url 'engine-detail' pk=engine.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="dvzo-buttons-bottom">
          {% if perms.train_management.add_vehicle %}
          <a href="{% url 'engine-create' %}" class="btn btn-primary btn-sm my-1 me-1">
            <i class="fas fa-plus"></i>
            {% translate "template.engine.add" %}
          </a>
          {% endif %}
          <button id="daySelectionBtn" class="btn btn-primary btn-sm my-1 me-1disabled">tmpGetSelections</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var $table = $('#engineListTable');
  var $button = $('#daySelectionBtn');

  $(function() {
      $button.click(function () {
          alert('getSelections: ' + JSON.stringify($table.bootstrapTable('getSelections')))
        })
    })



</script>
{% endblock content %}

train_management/templates/train_management/personnel_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "template.personnel.list.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">
  <div class="dvzo-header">
    {% translate "template.personnel.list.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <div class="card my-2">
          <div class="card-body">
            <div class="card-text">
              <table
                id="personnelListTable"
                data-toggle="table"
                data-classes="table table-hover table-condensed"
                data-striped="true"
                data-locale="de-DE"
                data-search="true"
                data-sort-name="name"
                data-sort-order="asc"
                data-pagination="true"
                data-page-size="15"
                data-page-list="[15, 25, 50, 100, 200, All]"
              >
                <thead>
                <tr>
                  <th data-field="state" data-checkbox="true">{% translate "table.state" %}</th>
                  <th data-field="id" data-visible="false">{% translate "table.id" %}</th>
                  <th data-field="name" data-sortable="true">{% translate "personnel.name" %}</th>
                  <th data-field="category" data-sortable="true">{% translate "personnel.category" %}</th>
                  <th data-field="status" data-sortable="true">{% translate "personnel.status" %}</th>
                  <th data-field="email" data-sortable="true">{% translate "personnel.email" %}</th>
                  <th data-field="mobile_phone" data-sortable="false">{% translate "personnel.mobile_phone" %}</th>
                  <th data-field="actions" data-sortable="false"></th>
                </tr>
                </thead>
                <tbody>
                {% for personnel in personnels %}
                <tr>
                  <td></td>
                  <td>{{ personnel.username }}</td>
                  <td>
                    <a href="{% url 'personnel-detail' pk=personnel.id %}">
                      {{ personnel.last_name }} {{ personnel.first_name }}
                    </a>
                  </td>
                  <td>
                    {% for category in personnel.category.all %}
                    {% include 'includes/personnel_category_type.html' with output=category.label category=category.type %}
                    {% endfor %}
                  </td>
                  <td>
                    {% if personnel.status == "active" %}
                    <span class="badge bg-success">{{ personnel.get_status_display }}</span>
                    {% elif personnel.status == "inactive" %}
                    <span class="badge bg-danger">{{ personnel.get_status_display }}</span>
                    {% else %}
                    {{ personnel.status }}
                    {% endif %}
                  </td>
                  <td>{{ personnel.email }}</td>
                  <td>{{ personnel.mobile_phone.as_national }}</td>
                  <td>
                    {% if perms.train_management.delete_personnel %}
                    <a href="{% url 'personnel-delete' pk=personnel.id %}">
                      <i class="fas fa-trash-alt text-danger"></i>
                    </a>
                    {% endif %}
                    {% if perms.train_management.change_personnel %}
                    <a href="{% url 'personnel-update' pk=personnel.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="dvzo-buttons-bottom">
          {% if perms.train_management.add_personnel %}
          <a href="{% url 'personnel-create' %}" class="btn btn-primary btn-sm my-1 me-1">
            <i class="fas fa-plus"></i>
            {% translate "template.personnel.add" %}
          </a>
          {% endif %}
          <button id="daySelectionBtn" class="btn btn-secondary btn-sm my-1 me-1 disabled">tmpGetSelections</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var $table = $('#personnelListTable');
  var $button = $('#daySelectionBtn');

  $(function() {
      $button.click(function () {
          alert('getSelections: ' + JSON.stringify($table.bootstrapTable('getSelections')))
        })
    })

</script>
{% endblock content %}

train_management/templates/train_management/personnelcategory_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "template.personnel_category.list.title" %}{% endblock %}

{% block content %}
<div class="dvzo-container">
  <div class="dvzo-header">
    {% translate "template.personnel_category.list.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <div class="card my-2">
          <div class="card-body">
            <div class="card-text">
              <table
                id="personnelCategoryListTable"
                data-toggle="table"
                data-classes="table table-hover table-condensed"
                data-striped="true"
                data-locale="de-DE"
                data-search="true"
                data-sort-name="label"
                data-sort-order="asc"
                data-pagination="true"
                data-page-size="15"
                data-page-list="[15, 25, 50, 100, 200, All]"
              >
                <thead>
                <tr>
                  <th data-field="state" data-checkbox="true">{% translate "table.state" %}</th>
                  <th data-field="id" data-visible="false">{% translate "table.id" %}</th>
                  <th data-field="label" data-sortable="true">{% translate "personnel_category.label" %}</th>
                  <th data-field="type" data-sortable="true">{% translate "personnel_category.type" %}</th>
                  <th data-field="actions" data-sortable="false"></th>
                </tr>
                </thead>
                <tbody>
                {% for category in personnel_categories %}
                <tr>
                  <td></td>
                  <td>{{ category.id }}</td>
                  <td>{{ category.label }}</td>
                  <td>
                    {% include 'includes/personnel_category_type.html' with output=category.get_type_display category=category.type%}
                  </td>
                  <td>
                    {% if perms.train_management.delete_personnelcategory %}
                    <a href="{% url 'personnel-category-delete' pk=category.id %}">
                      <i class="fas fa-trash-alt text-danger"></i>
                    </a>
                    {% endif %}
                    {% if perms.train_management.change_personnelcategory %}
                    <a href="{% url 'personnel-category-detail' pk=category.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="dvzo-buttons-bottom">
          {% if perms.train_management.add_personnelcategory %}
          <a href="{% url 'personnel-category-create' %}" class="btn btn-primary btn-sm">
            <i class="fas fa-plus"></i>
            {% translate "template.personnel_category.add" %}
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
  const $table = $('#personnelCategoryListTable');
</script>
{% endblock scripts %}