base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

dvzo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('train_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("shifts/", include("shifts.urls")),
]

training/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.CourseListView.as_view(), name='training-home'),

    path('training-module/', views.TrainingModuleListView.as_view(), name='training-module-list'),
    path('training-module/<int:pk>/', views.TrainingModuleUpdateView.as_view(), name='training-module-update'),
    path('training-module/add/', views.TrainingModuleCreateView.as_view(), name='training-module-create'),
    path('training-module/<int:pk>/delete/', views.TrainingModuleDeleteView.as_view(), name='training-module-delete'),

    path('training/', views.TrainingListView.as_view(), name='training-list'),
    path('training/<int:pk>/', views.TrainingDetailView.as_view(), name='training-detail'),
    path('training/<int:pk>/edit/', views.TrainingUpdateView.as_view(), name='training-update'),
    path('training/add/', views.TrainingCreateView.as_view(), name='training-create'),
    path('training/<int:pk>/delete/', views.TrainingDeleteView.as_view(), name='training-delete'),

    path('training/date/<int:pk>/edit/', views.TrainingDateUpdateView.as_view(), name='training-date-update'),
    path('training/<int:pk>/date/add/', views.TrainingDateCreateView.as_view(), name='training-date-create'),
    path('training//date/<int:pk>/delete/', views.TrainingDateDeleteView.as_view(), name='training-date-delete'),

    path('participant/<int:pk>/edit/', views.ParticipantUpdateView.as_view(), name='participant-update'),
    path('<int:pk>/participant/add/', views.ParticipantCreateView.as_view(), name='participant-create'),
    path('participant/<int:pk>/delete/', views.ParticipantDeleteView.as_view(), name='participant-delete'),
]

training/models/attendance.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel
from training.models import Participant, TrainingDate


class Attendance(AbstractDvzoModel):
    class Meta:
        verbose_name = _("attendance.singular")
        verbose_name_plural = _("attendance.plural")

    training_date = models.ForeignKey(TrainingDate, on_delete=models.DO_NOTHING)
    participant = models.ForeignKey(Participant, on_delete=models.DO_NOTHING)
    attended = models.BooleanField(_("attendance.attended"))

training/models/medical_fitness.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel, Personnel
from training.models import TrainingModule


class MedicalFitnessLevel(AbstractDvzoModel):
    class Meta:
        verbose_name = _("medical_fitness_level.singular")
        verbose_name_plural = _("medical_fitness_level.plural")

    label = models.CharField(_("medical_fitness_level.label"), max_length=200)

    def __str__(self):
        return self.label


class MedicalFitness(AbstractDvzoModel):
    class Meta:
        verbose_name = _("medical_fitness.singular")
        verbose_name_plural = _("medical_fitness.plural")

    personnel = models.ForeignKey(Personnel, on_delete=models.DO_NOTHING)
    level = models.ForeignKey(MedicalFitnessLevel, on_delete=models.DO_NOTHING)
    date = models.DateField(_("medical_fitness.date"), null=True, blank=True)

    def __str__(self):
        return self.label

training/models/participant.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel, Personnel
from training.models import Training


class Participant(AbstractDvzoModel):
    class Meta:
        verbose_name = _("participant.singular")
        verbose_name_plural = _("participant.plural")

    training = models.ForeignKey(Training, on_delete=models.DO_NOTHING)
    personnel = models.ForeignKey(Personnel, on_delete=models.DO_NOTHING)
    attended = models.BooleanField(_("participant.attended"))
    passed = models.BooleanField(_("participant.passed"))

    def __str__(self):
        return "%s %s" % (self.personnel.first_name, self.personnel.last_name)

training/models/periodic_exam.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel, Personnel
from training.models import Qualification


class PeriodicExam(AbstractDvzoModel):
    class Meta:
        verbose_name = _("periodic_exam.singular")
        verbose_name_plural = _("periodic_exam.plural")

    personnel = models.ForeignKey(Personnel, on_delete=models.DO_NOTHING)
    qualification = models.ForeignKey(Qualification, on_delete=models.DO_NOTHING)
    date = models.DateField(_("periodic_exam.date"), null=True, blank=True)

    def __str__(self):
        return self.label

training/models/personnel_qualification.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel, Personnel
from training.models import Qualification


class PersonnelQualification(AbstractDvzoModel):
    class Meta:
        verbose_name = _("personnel_qualification.singular")
        verbose_name_plural = _("personnel_qualification.plural")

    personnel = models.ForeignKey(Personnel, on_delete=models.DO_NOTHING)
    qualification = models.ForeignKey(Qualification, on_delete=models.DO_NOTHING)
    valid_until = models.DateField(_("personnel_qualification.valid_until"))
    automatically_added = models.BooleanField(_("personnel_qualification.automatically_added"))

    def __str__(self):
        return self.qualification

training/models/qualification.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel


class Qualification(AbstractDvzoModel):
    class Meta:
        verbose_name = _("qualification.singular")
        verbose_name_plural = _("qualification.plural")

    class QualificationType(models.TextChoices):
        VTE = "vte", _("qualification.type.vte")
        ZSTEBV = "zstebv", _("qualification.type.zstebv")
        DVZO = "dvzo", _("qualification.type.dvzo")

    label = models.CharField(_("qualification.label"), blank=True, max_length=200)
    description = models.TextField(_("qualification.description"))
    type = models.CharField(_("qualification.type"), max_length=80, choices=QualificationType.choices)
    valid_years = models.IntegerField(_("qualification.valid_years"))

    def __str__(self):
        return self.label

training/models/requirement.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel
from training.models import MedicalFitnessLevel, PeriodicExam, Qualification, TrainingModule


class Requirement(AbstractDvzoModel):
    class Meta:
        verbose_name = _("requirement.singular")
        verbose_name_plural = _("requirement.plural")

    qualification = models.ForeignKey(Qualification, on_delete=models.DO_NOTHING)
    module = models.ManyToManyField(TrainingModule, blank=True)
    medical_fitness = models.ForeignKey(MedicalFitnessLevel, null=True, blank=True, on_delete=models.DO_NOTHING)
    periodic_exam = models.ForeignKey(PeriodicExam, null=True, blank=True, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.qualification

training/models/training.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel, Personnel
from training.models import TrainingModule


class Training(AbstractDvzoModel):
    class Meta:
        verbose_name = _("training.singular")
        verbose_name_plural = _("training.plural")

    label = models.CharField(_("training.label"), max_length=200)
    course_label = models.CharField(_("training.course_label"), max_length=200)
    module = models.ForeignKey(TrainingModule, on_delete=models.DO_NOTHING)
    responsible = models.ForeignKey(Personnel, null=True, blank=True, on_delete=models.DO_NOTHING)
    start_date = models.DateField(_("training.start_date"), null=True, blank=True)
    end_date = models.DateField(_("training.end_date"), null=True, blank=True)

    def __str__(self):
        return self.label


class TrainingDate(AbstractDvzoModel):
    class Meta:
        verbose_name = _("training_date.singular")
        verbose_name_plural = _("training_date.plural")

    label = models.CharField(_("training_date.label"), max_length=200, null=True, blank=True)
    responsible = models.ManyToManyField(Personnel, blank=True, related_name='training_date_responsible')
    start_datetime = models.DateTimeField(_("training_date.start_date"), null=True, blank=True)
    end_datetime = models.DateTimeField(_("training_date.end_date"), null=True, blank=True)
    training = models.ForeignKey(Training, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.label

training/forms/attendance.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import Attendance


class AttendanceModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = Attendance
        fields = ['training_date',
                  'participant',
                  'attended'
                  ]

training/forms/medical_fitness.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import MedicalFitness, MedicalFitnessLevel


class MedicalFitnessModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = MedicalFitness
        fields = ['personnel',
                  'level',
                  'date'
                  ]


class MedicalFitnessLevelModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = MedicalFitnessLevel
        fields = ['label']

training/forms/participant.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import Participant


class ParticipantForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = Participant
        fields = ['personnel',
                  'attended',
                  'passed'
                  ]

training/forms/periodic_exam.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import PeriodicExam


class PeriodicExamModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = PeriodicExam
        fields = ['personnel',
                  'qualification',
                  'date'
                  ]

training/forms/personnel_qualification.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import PersonnelQualification


class PersonnelQualificationModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = PersonnelQualification
        fields = ['personnel',
                  'qualification',
                  'valid_until',
                  'automatically_added'
                  ]

training/forms/qualification.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import Qualification


class QualificationModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = Qualification
        fields = ['label',
                  'description',
                  'type',
                  'valid_years'
                  ]

training/forms/requirement.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import Requirement


class RequirementForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = Requirement
        fields = ['qualification',
                  'module',
                  'medical_fitness',
                  'periodic_exam'
                  ]

training/forms/training.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import Training, TrainingDate


class TrainingForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = Training
        fields = ['label',
                  'course_label',
                  'module',
                  'responsible',
                  'start_date',
                  'end_date'
                  ]


class TrainingDateForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = TrainingDate
        fields = ['label',
                  'responsible',
                  'start_datetime',
                  'end_datetime'
                  ]

training/forms/training_module.py
from django.forms import ModelForm
from tapeforms.contrib.bootstrap import BootstrapTapeformMixin

from training.models import TrainingModule


class TrainingModuleForm(BootstrapTapeformMixin, ModelForm):
    field_container_css_class = 'mb-3'

    class Meta:
        model = TrainingModule
        fields = ['label',
                  'label_short',
                  'description'
                  ]

training/views/participant.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from training.forms import ParticipantForm
from training.models import Training, Participant


@method_decorator(login_required, name='dispatch')
class ParticipantUpdateView(generic.UpdateView):
    model = Participant
    form_class = ParticipantForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("training-detail", kwargs={'pk': self.object.training.id})


@method_decorator(login_required, name='dispatch')
class ParticipantCreateView(generic.CreateView):
    model = Participant
    form_class = ParticipantForm
    template_name_suffix = "_create_form"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, pk, **kwargs):
        self.training = get_object_or_404(Training, pk=pk)
        return super().post(request, **kwargs)

    def form_valid(self, form):
        form.instance.training = self.training
        return_value = super().form_valid(form)
        return return_value

    def get_success_url(self):
        return reverse_lazy("training-detail", kwargs={'pk': self.object.training.id})


@method_decorator(login_required, name='dispatch')
class ParticipantDeleteView(generic.DeleteView):
    model = Participant

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy("training-detail", kwargs={'pk': self.object.training.id})

training/views/training.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from training.forms import TrainingForm
from training.models import Participant, Training, TrainingDate


@method_decorator(login_required, name='dispatch')
class TrainingListView(generic.ListView):
    context_object_name = "trainings"

    def get_queryset(self):
        return Training.objects.all()


@method_decorator(login_required, name='dispatch')
class TrainingDetailView(generic.DetailView):
    model = Training
    form_class = TrainingForm
    template_name_suffix = "_detail_form"

    def get_context_data(self, **kwargs):
        dates = TrainingDate.objects.filter(training=self.object.id).order_by("start_datetime")
        participants = Participant.objects.filter(training=self.object.id).order_by("personnel")
        return super().get_context_data(dates=dates, participants=participants, **kwargs)


@method_decorator(login_required, name='dispatch')
class TrainingUpdateView(generic.UpdateView):
    model = Training
    form_class = TrainingForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("training-detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class TrainingCreateView(generic.CreateView):
    model = Training
    form_class = TrainingForm
    template_name_suffix = "_create_form"

    def get_success_url(self):
        return reverse_lazy("training-detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class TrainingDeleteView(generic.DeleteView):
    model = Training
    template_name = "train_management/confirm_delete.html"
    success_url = reverse_lazy("training-list")

training/templates/training/participant_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.participant.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.participant.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.participant.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const choice = new Choices('#id_personnel', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

training/templates/training/participant_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.participant.update.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {{ object.label }}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form action="{% url 'participant-update' pk=object.id %}" method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
            {% include 'includes/card_footer.html' %}
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.participant.submit' %}" class="btn btn-primary btn-sm my-1 me-1">
            <a href="{% url 'training-detail' pk=object.training.id %}" class="btn btn-primary btn-sm my-1 me-1">
              {% translate "app.back" %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const choice = new Choices('#id_personnel', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

training/templates/training/training_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.training.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.training.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.training.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

training/templates/training/training_detail_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "template.training.detail.title" %} - {{ object.label }}{% endblock %}

{% block content %}

<div class="dvzo-container">
  <div class="dvzo-header">{{ object.label }}</div>
  <div class="dvzo-content">
    <div class="dvzo-button-top">
      <div class="card my-2">
        <div class="card-body">
          <div class="card-text">
            <a href='{% url "training-list" %}' class="btn btn-primary btn-sm my-1 me-1">
              <i class="fas fa-list"></i>
              {% translate "Back to list" %}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="card my-2">
        <div class="card-body">
          <div class="card-title">{% translate "app.master_data" %}</div>
          <div class="card-text">
            <table class="table table-sm dvzo-25">
              <thead>
              <th></th>
              <th></th>
              </thead>
              <tbody>
              <tr>
                <th>{% translate "training.label" %}</th>
                <td>{{object.label}}</td>
              </tr>
              <tr>
                <th>{% translate "training.course_label" %}</th>
                <td>{{object.course_label}}</td>
              </tr>
              <tr>
                <th>{% translate "training.module" %}</th>
                <td>{{object.module}}</td>
              </tr>
              <tr>
                <th>{% translate "training.responsible" %}</th>
                <td>{{object.responsible}}</td>
              </tr>
              <tr>
                <th>{% translate "training.start_date" %}</th>
                <td>{{object.start_date}}</td>
              </tr>
              <tr>
                <th>{% translate "training.end_date" %}</th>
                <td>{{object.end_date}}</td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        {% include 'includes/card_footer.html' %}
      </div>
      <div class="dvzo-button-bottom mb-4">
        <a href='{% url "training-update" pk=object.id %}' class="btn btn-primary btn-sm my-1 me-1">
          <i class="far fa-edit"></i>
          {% translate "Edit" %}
        </a>
      </div>
    </div>
    <div class="col">
      <div class="card my-2">
        <div class="card-body">
          <div class="card-title">{% translate "template.training.training_dates" %}</div>
          <div class="card-text">
            <table class="table table-sm dvzo-25">
              <thead>
              <th>{% translate "training.training_date.date" %}</th>
              <th>{% translate "training.training_date.label" %}</th>
              <th>{% translate "training.training_date.responsible" %}</th>
              <th></th>
              </thead>
              <tbody>
              {% for date in dates %}
              <tr>
                <td>{{date.start_datetime}} - {{date.start_datetime}}</td>
                <td>{{date.label}}</td>
                <td>
                  {% for person in date.responsible.all %}
                  {{person}}<br>
                  {% endfor %}
                </td>
                <td>
                  <a href="{% url 'training-date-delete' pk=date.id %}">
                      <i class="fas fa-trash-alt text-danger"></i>
                    </a>&nbsp;
                    <a href="{% url 'training-date-update' pk=date.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                </td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="dvzo-button-bottom mb-4">
        <a href='{% url "training-date-create" pk=object.id %}' class="btn btn-primary btn-sm my-1 me-1">
          <i class="fas fa-plus"></i>
          {% translate "template.training.training_date.add" %}
        </a>
      </div>
    </div>
  </div>




      <div class="row">
        <div class="col">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-title">{% translate "template.training.participants" %}</div>
              <div class="card-text">
                <table class="table table-sm dvzo-25">
                  <thead>
                  <th>{% translate "template.training.participant" %}</th>
                  <th>{% translate "template.training.attended" %}</th>
                  <th>{% translate "template.training.passed" %}</th>
                  <th></th>
                  </thead>
                  <tbody>
                  {% for participant in participants %}
                  <tr>
                    <td>{{ participant }}</td>
                    <td>{{ participant.attended }}</td>
                    <td>{{ participant.passed }}</td>
                    <td>
                      <a href="{% url 'participant-delete' pk=participant.id %}">
                      <i class="fas fa-trash-alt text-danger"></i>
                    </a>&nbsp;
                    <a href="{% url 'participant-update' pk=participant.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="dvzo-button-bottom mb-4">
        <a href='{% url "participant-create" pk=object.id %}' class="btn btn-primary btn-sm my-1 me-1">
          <i class="fas fa-plus"></i>
          {% translate "training.participants.add" %}
        </a>
      </div>
      </div>
    </div>

    {% endblock content %}

training/templates/training/training_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.training.update.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {{ object.label }}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form action="{% url 'training-update' pk=object.id %}" method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
            {% include 'includes/card_footer.html' %}
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.training.submit' %}" class="btn btn-primary btn-sm my-1 me-1">
            <a href="{% url 'training-detail' pk=object.id %}" class="btn btn-primary btn-sm my-1 me-1">
              {% translate "app.back" %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

training/templates/training/trainingdate_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.training_date.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.training_date.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.training_date.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const multipleCancelButton = new Choices('#id_responsible', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

training/templates/training/trainingdate_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.training_date.update.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {{ object.label }}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form action="{% url 'training-date-update' pk=object.id %}" method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
            {% include 'includes/card_footer.html' %}
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.training_date.submit' %}" class="btn btn-primary btn-sm my-1 me-1">
            <a href="{% url 'training-detail' pk=object.training.id %}" class="btn btn-primary btn-sm my-1 me-1">
              {% translate "app.back" %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const multipleCancelButton = new Choices('#id_responsible', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

training/templates/training/trainingmodule_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.training_module.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.training_module.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.training_module.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}