base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

dvzo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('train_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("shifts/", include("shifts.urls")),
]

uniforms/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('article/', views.ArticleListView.as_view(), name='article-list'),
    path('article/hat/add/', views.HatArticleCreateView.as_view(), name='article-hat-create'),
    path('article/shirt/add/', views.ShirtArticleCreateView.as_view(), name='article-shirt-create'),
    path('article/vest/add/', views.VestArticleCreateView.as_view(), name='article-vest-create'),
    path('article/coat/add/', views.CoatArticleCreateView.as_view(), name='article-coat-create'),
    path('article/tie/add/', views.TieArticleCreateView.as_view(), name='article-tie-create'),
    path('article/trousers/add/', views.TrousersArticleCreateView.as_view(), name='article-trousers-create'),
    path('article/shoes/add/', views.ShoesArticleCreateView.as_view(), name='article-shoes-create'),
    path('article/misc/add/', views.MiscArticleCreateView.as_view(), name='article-misc-create'),
    path('article/hat/<int:pk>/', views.HatArticleUpdateView.as_view(), name='article-hat-update'),
    path('article/shirt/<int:pk>/', views.ShirtArticleUpdateView.as_view(), name='article-shirt-update'),
    path('article/vest/<int:pk>/', views.VestArticleUpdateView.as_view(), name='article-vest-update'),
    path('article/coat/<int:pk>/', views.CoatArticleUpdateView.as_view(), name='article-coat-update'),
    path('article/tie/<int:pk>/', views.TieArticleUpdateView.as_view(), name='article-tie-update'),
    path('article/trousers/<int:pk>/', views.TrousersArticleUpdateView.as_view(), name='article-trousers-update'),
    path('article/shoes/<int:pk>/', views.ShoesArticleUpdateView.as_view(), name='article-shoes-update'),
    path('article/misc/<int:pk>/', views.MiscArticleUpdateView.as_view(), name='article-misc-update'),

    path('renter/', views.RenterListView.as_view(), name='renter-list'),
    path('renter/add/', views.RenterCreateView.as_view(), name='renter-create'),
    path('renter/<int:pk>/', views.RenterDetailView.as_view(), name='renter-detail'),
    path('renter/<int:pk>/edit/', views.RenterUpdateView.as_view(), name='renter-update'),
    path('renter/<int:pk>/delete/', views.RenterDeleteView.as_view(), name='renter-delete'),

    path('rent/', views.RentListView.as_view(), name='rent-list'),
    path('rent/add/', views.RentCreateView.as_view(), name='rent-create'),
    path('rent/<int:pk>/', views.RentDetailView.as_view(), name='rent-detail'),
    path('rent/<int:pk>/edit/', views.RentUpdateView.as_view(), name='rent-update'),
    path('rent/<int:pk>/delete/', views.RentDeleteView.as_view(), name='rent-delete'),

    path('rent/article/add/<int:pk>', views.ArticleRentCreateView.as_view(), name='rent-article-create'),
    path('rent/article/<int:pk>/', views.ArticleRentUpdateView.as_view(), name='rent-article-update'),
    path('rent/article/<int:pk>/delete/', views.ArticleRentDeleteView.as_view(), name='rent-article-delete'),

    path('rent/<int:pk>/print/', views.RentPdfView.as_view(template_name="pdf/rent.html"), name='rent-print'),



    path('let/', views.LetListView.as_view(), name='let-list'),
    path('let/add/', views.LetCreateView.as_view(), name='let-create'),
    path('let/<int:pk>/', views.LetDetailView.as_view(), name='let-detail'),
    path('let/<int:pk>/edit/', views.LetUpdateView.as_view(), name='let-update'),
    path('let/<int:pk>/delete/', views.LetDeleteView.as_view(), name='let-delete'),

    path('let/article/add/<int:pk>', views.ArticleLetCreateView.as_view(), name='let-article-create'),
    path('let/article/<int:pk>/', views.ArticleLetUpdateView.as_view(), name='let-article-update'),
    path('let/article/<int:pk>/delete/', views.ArticleLetDeleteView.as_view(), name='let-article-delete'),

    path('let/<int:pk>/print/', views.LetPdfView.as_view(template_name="pdf/let.html"), name='let-print'),
]

uniforms/models/article.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel


class Article(AbstractDvzoModel):
    class Meta:
        verbose_name = _("article.singular")
        verbose_name_plural = _("article.plural")

    class ArticleCategory(models.TextChoices):
        COAT = "coat", _("article.article_category.coat")
        HAT = "hat", _("article.article_category.hat")
        MISC = "misc", _("article.article_category.misc")
        SHIRT = "shirt", _("article.article_category.shirt")
        SHOES = "shoes", _("article.article_category.shoes")
        VEST = "vest", _("article.article_category.vest")
        TIE = "tie", _("article.article_category.tie")
        TROUSERS = "trousers", _("article.article_category.trousers")

    class ArticleStatus(models.TextChoices):
        ACTIVE = "active", _("article.article_status.active")
        INACTIVE = "inactive", _("article.article_status.inactive")

    label = models.CharField(_("article.label"), max_length=200)
    category = models.CharField(_("article.category"), max_length=80, choices=ArticleCategory.choices)
    status = models.CharField(_("article.status"), max_length=80, choices=ArticleStatus.choices,
                              default=ArticleStatus.ACTIVE)
    amount = models.IntegerField(_("article.amount"), null=True, blank=True)
    price = models.DecimalField(_("article.price"), max_digits=5, decimal_places=2)

    def __str__(self):
        return self.label


class HatArticle(Article):
    class Meta:
        verbose_name = _("article.hat.singular")
        verbose_name_plural = _("article.hat.plural")

    circumference = models.IntegerField(_("article.hat.circumference"), null=True, blank=True)


class ShirtArticle(Article):
    class Meta:
        verbose_name = _("article.shirt.singular")
        verbose_name_plural = _("article.shirt.plural")

    size = models.IntegerField(_("article.shirt.size"), null=True, blank=True)


class VestArticle(Article):
    class Meta:
        verbose_name = _("article.vest.singular")
        verbose_name_plural = _("article.vest.plural")

    size = models.IntegerField(_("article.vest.size"), null=True, blank=True)


class CoatArticle(Article):
    class Meta:
        verbose_name = _("article.coat.singular")
        verbose_name_plural = _("article.coat.plural")

    size = models.IntegerField(_("article.coat.size"), null=True, blank=True)


class TieArticle(Article):
    class Meta:
        verbose_name = _("article.tie.singular")
        verbose_name_plural = _("article.tie.plural")

    length = models.IntegerField(_("article.tie.length"), null=True, blank=True)


class TrousersArticle(Article):
    class Meta:
        verbose_name = _("article.trousers.singular")
        verbose_name_plural = _("article.trousers.plural")

    waist = models.IntegerField(_("article.trousers.waist"), null=True, blank=True)
    length = models.IntegerField(_("article.trousers.length"), null=True, blank=True)


class ShoesArticle(Article):
    class Meta:
        verbose_name = _("article.shoes.singular")
        verbose_name_plural = _("article.shoes.plural")

    size = models.IntegerField(_("article.shoes.size"), null=True, blank=True)


class MiscArticle(Article):
    class Meta:
        verbose_name = _("article.misc.singular")
        verbose_name_plural = _("article.misc.plural")

    class MiscArticleType(models.TextChoices):
        WHISTLE = "whistle", _("article.misc_article_type.whistle")

    type = models.CharField(_("article.misc.type"), max_length=80, choices=MiscArticleType.choices)

uniforms/models/let.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel, Personnel
from uniforms.models import Article


class Let(AbstractDvzoModel):
    class Meta:
        verbose_name = _("let.singular")
        verbose_name_plural = _("let.plural")

    class LetReturned(models.TextChoices):
        YES = "yes", _("let.returned.yes")
        NO = "no", _("let.returned.no")

    personnel = models.ForeignKey(Personnel, on_delete=models.DO_NOTHING)
    start = models.DateField(_("let.start"))
    end = models.DateField(_("let.end"), null=True, blank=True)
    returned = models.CharField(_("let.returned"), max_length=80, choices=LetReturned.choices, default=LetReturned.NO)


class ArticleLet(AbstractDvzoModel):
    class Meta:
        verbose_name = _("article_let.singular")
        verbose_name_plural = _("article_let.plural")

    let = models.ForeignKey(Let, on_delete=models.DO_NOTHING)
    article = models.ForeignKey(Article, on_delete=models.DO_NOTHING)
    amount = models.IntegerField(_("article_let.amount"))

uniforms/models/rent.py
from dateutil import relativedelta

from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from train_management.models import AbstractDvzoModel
from uniforms.models import Article, Renter


class Rent(AbstractDvzoModel):
    class Meta:
        verbose_name = _("rent.singular")
        verbose_name_plural = _("rent.plural")

    class RentReturned(models.TextChoices):
        YES = "yes", _("rent.returned.yes")
        NO = "no", _("rent.returned.no")

    renter = models.ForeignKey(Renter, on_delete=models.DO_NOTHING)
    start = models.DateField(_("rent.start"))
    end = models.DateField(_("rent.end"))
    duration = models.IntegerField(_("rent.duration"), blank=True, null=True)
    returned = models.CharField(_("rent.returned"), max_length=80, choices=RentReturned.choices,
                                default=RentReturned.NO)
    billed = models.BooleanField(_("rent.billed"))
    total_per_month = models.DecimalField(_("rent.total_per_month"), max_digits=8, decimal_places=2, null=True)
    total = models.DecimalField(_("rent.total"), max_digits=8, decimal_places=2, null=True)

    def save(self, *args, **kwargs):
        if self.end is not None:
            start = self.start
            end = self.end
            total_per_month = self.total_per_month
            duration = relativedelta.relativedelta(end, start).months
            if duration == 0:
                duration = 1
            self.duration = duration
            self.total = duration * total_per_month
            super(Rent, self).save(*args, **kwargs)


class ArticleRent(AbstractDvzoModel):
    class Meta:
        verbose_name = _("article_rent.singular")
        verbose_name_plural = _("article_rent.plural")

    rent = models.ForeignKey(Rent, on_delete=models.DO_NOTHING)
    article = models.ForeignKey(Article, on_delete=models.DO_NOTHING)
    amount = models.DecimalField(_("article_rent.amount"), max_digits=2, decimal_places=0)
    total_per_month = models.DecimalField(_("article_rent.total_per_month"), max_digits=8, decimal_places=2, null=True,
                                          editable=False)

    def get_total_per_month(self):
        result = self.amount * self.article.price
        return result

    def save(self, *args, **kwargs):
        self.total_per_month = self.get_total_per_month()
        super(ArticleRent, self).save(*args, **kwargs)


@receiver(post_save, sender=ArticleRent)
def do_sums_on_rent_save(sender, instance, created, *args, **kwargs):
    rent = Rent.objects.get(id=instance.rent.id)
    article_rents = ArticleRent.objects.filter(rent=rent)
    total_per_month = article_rents.aggregate(Sum('total_per_month'))
    rent.total_per_month = total_per_month['total_per_month__sum']
    rent.save()


@receiver(post_delete, sender=ArticleRent)
def do_sums_on_rent_delete(sender, instance, *args, **kwargs):
    rent = Rent.objects.get(id=instance.rent.id)
    article_rents = ArticleRent.objects.filter(rent=rent)
    total_per_month = article_rents.aggregate(Sum('total_per_month'))
    rent.total_per_month = total_per_month['total_per_month__sum']
    rent.save()

uniforms/views/let.py
from django.contrib.auth.decorators import login_required
from django.db.models import F, ExpressionWrapper, DecimalField
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from uniforms.forms import ArticleLetForm, LetForm
from uniforms.models import ArticleLet, Let


@method_decorator(login_required, name='dispatch')
class LetListView(generic.ListView):
    context_object_name = "lets"

    def get_queryset(self):
        return Let.objects.all()


@method_decorator(login_required, name='dispatch')
class LetDetailView(generic.DetailView):
    model = Let
    template_name_suffix = "_detail_form"

    def get_context_data(self, **kwargs):
        article_lets = ArticleLet.objects.filter(let=self.object)
        return super().get_context_data(
            article_lets=article_lets,
            **kwargs)


@method_decorator(login_required, name='dispatch')
class LetUpdateView(generic.UpdateView):
    model = Let
    form_class = LetForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("let-detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class LetCreateView(generic.CreateView):
    model = Let
    form_class = LetForm
    template_name_suffix = "_create_form"

    def get_success_url(self):
        return reverse_lazy("let-detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class LetDeleteView(generic.DeleteView):
    model = Let
    template_name = "uniforms/confirm_delete.html"
    success_url = reverse_lazy("let-list")


@method_decorator(login_required, name='dispatch')
class ArticleLetUpdateView(generic.UpdateView):
    model = ArticleLet
    form_class = ArticleLetForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("let-detail", kwargs={'pk': self.object.let.id})


@method_decorator(login_required, name='dispatch')
class ArticleLetCreateView(generic.CreateView):
    model = ArticleLet
    form_class = ArticleLetForm
    template_name_suffix = "_create_form"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, pk, **kwargs):
        self.let = get_object_or_404(Let, pk=pk)
        return super().post(request, **kwargs)

    def form_valid(self, form):
        form.instance.let = self.let
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("let-detail", kwargs={'pk': self.object.let.id})


@method_decorator(login_required, name='dispatch')
class ArticleLetDeleteView(generic.DeleteView):
    model = ArticleLet

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy("let-detail", kwargs={'pk': self.object.let.id})

uniforms/views/pdf_weasyprint.py
import functools
import ssl

from django_weasyprint import WeasyTemplateResponseMixin
from django_weasyprint.utils import django_url_fetcher
from django_weasyprint.views import WeasyTemplateResponse

from uniforms.views import LetDetailView, RentDetailView


class CustomWeasyTemplateResponse(WeasyTemplateResponse):
    # customized response class to change the default URL fetcher
    def get_url_fetcher(self):
        # disable host and certificate check
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        return functools.partial(django_url_fetcher, ssl_context=context)


class RentPdfView(WeasyTemplateResponseMixin, RentDetailView):
    pdf_attachment = False
    response_class = CustomWeasyTemplateResponse


class LetPdfView(WeasyTemplateResponseMixin, LetDetailView):
    pdf_attachment = False
    response_class = CustomWeasyTemplateResponse

uniforms/views/renter.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from uniforms.forms import RenterForm
from uniforms.models import Renter


@method_decorator(login_required, name='dispatch')
class RenterListView(generic.ListView):
    context_object_name = "renters"

    def get_queryset(self):
        return Renter.objects.all()


@method_decorator(login_required, name='dispatch')
class RenterDetailView(generic.DetailView):
    model = Renter
    context_object_name = "renters"
    template_name_suffix = "_detail_form"


@method_decorator(login_required, name='dispatch')
class RenterUpdateView(generic.UpdateView):
    model = Renter
    form_class = RenterForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("renter-detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class RenterCreateView(generic.CreateView):
    model = Renter
    form_class = RenterForm
    template_name_suffix = "_create_form"

    def get_success_url(self):
        return reverse_lazy("renter-detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class RenterDeleteView(generic.DeleteView):
    model = Renter
    template_name = "uniforms/confirm_delete.html"
    success_url = reverse_lazy("renter-list")

uniforms/templates/uniforms/article_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "template.article.list.title" %}{% endblock %}

{% block content %}
<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.article.list.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <div class="card my-2">
          <div class="card-body">
            <div class="card-text">
              <table
                id="articleListTable"
                data-toggle="table"
                data-classes="table table-hover table-condensed"
                data-striped="true"
                data-locale="de-DE"
                data-search="true"
                data-sort-name="label"
                data-sort-order="asc"
                data-pagination="true"
                data-page-size="15"
                data-page-list="[15, 25, 50, 100, 200, All]"
              >
                <thead>
                <tr>
                  <th data-field="state" data-checkbox="true">{% translate "table.state" %}</th>
                  <th data-field="id" data-visible="false">{% translate "table.id" %}</th>
                  <th data-field="label" data-sortable="true">{% translate "article.label" %}</th>
                  <th data-field="category" data-sortable="true">{% translate "article.category" %}</th>
                  <th data-field="amount" data-sortable="true">{% translate "article.amount" %}</th>
                  <th data-field="price" data-sortable="true">{% translate "article.price" %}</th>
                  <th data-field="status" data-sortable="true">{% translate "article.status" %}</th>
                  <th data-field="actions" data-sortable="false"></th>
                </tr>
                </thead>
                <tbody>
                {% for article in articles %}
                <tr>
                  <td></td>
                  <td>{{ article.id }}</td>
                  <td>{{ article.label }}</td>
                  <td>
                    <span class="badge bg-secondary"> {{ article.get_category_display }}</span>
                  </td>
                  <td>{{ article.amount }}</td>
                  <td>{{ article.price }}</td>
                  <td>
                    {% if article.status == "active" %}
                    <span class="badge bg-success">{{ article.get_status_display }}</span>
                    {% elif article.status == "inactive" %}
                    <span class="badge bg-danger">{{ article.get_status_display }}</span>
                    {% else %}
                    {{ article.status }}
                    {% endif %}
                  </td>
                  <td>
                    {% if article.category == "coat" %}
                    <a href="{% url 'article-coat-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "hat" %}
                    <a href="{% url 'article-hat-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "misc" %}
                    <a href="{% url 'article-misc-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "shirt" %}
                    <a href="{% url 'article-shirt-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "shoes" %}
                    <a href="{% url 'article-shoes-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "vest" %}
                    <a href="{% url 'article-vest-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "tie" %}
                    <a href="{% url 'article-tie-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% elif article.category == "trousers" %}
                    <a href="{% url 'article-trousers-update' pk=article.id %}">
                      <i class="far fa-edit"></i>
                    </a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="dvzo-buttons-bottom">
          <div class="dropdown">
            <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="newArticleButton"
                    data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-plus"></i>
              {% translate "template.article.new" %}
            </button>
            <ul class="dropdown-menu" aria-labelledby="newArticleButton">
              <li><a class="dropdown-item" href="{% url 'article-coat-create' %}">{% translate "template.article.new.coat" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-hat-create' %}">{% translate "template.article.new.hat" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-misc-create' %}">{% translate "template.article.new.misc" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-shirt-create' %}">{% translate "template.article.new.shirt" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-shoes-create' %}">{% translate "template.article.new.shoes" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-vest-create' %}">{% translate "template.article.new.vest" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-tie-create' %}">{% translate "template.article.new.tie" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'article-trousers-create' %}">{% translate "template.article.new.trousers" %}</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var $table = $('#articleListTable');
  var $button = $('#daySelectionBtn');

  $(function () {
    $button.click(function () {
      alert('getSelections: ' + JSON.stringify($table.bootstrapTable('getSelections')))
    })
  })


</script>
{% endblock content %}

uniforms/templates/uniforms/article_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.article.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">
  <div class="dvzo-header">
    {% translate "template.article.create.header" %}
  </div>
  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          {% csrf_token %}
          {% for fieldset in form.get_fieldsets %}
          <div class="card my-2">
            <div class="card-body">
              <div class="card-title">{{ fieldset.extra.title }}</div>
              <div class="card-text">{% form fieldset %}</div>
            </div>
          </div>
          {% endfor %}
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'app.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

uniforms/templates/uniforms/articlelet_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.let_article.update.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">
  <div class="dvzo-header">
    {{ object.label }}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form action="{% url 'let-article-update' pk=object.id %}" method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
            {% include 'includes/card_footer.html' %}
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.let_article.submit' %}" class="btn btn-primary btn-sm my-1 me-1">
            <a href="{% url 'let-detail' object.let.pk %}" class="btn btn-primary btn-sm my-1 me-1">
              {% translate "Back to list" %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const multipleCancelButton = new Choices('#id_article', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

uniforms/templates/uniforms/articlerent_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.rent_article.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.rent_article.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.rent_article.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const multipleCancelButton = new Choices('#id_article', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

uniforms/templates/uniforms/let_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.let.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.let.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.let.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const multipleCancelButton = new Choices('#id_personnel', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}

uniforms/templates/uniforms/rent_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% load tapeforms %}

{% block title %}{% translate "template.rent.create.title" %}{% endblock %}

{% block content %}

<div class="dvzo-container">

  <div class="dvzo-header">
    {% translate "template.rent.create.header" %}
  </div>

  <div class="dvzo-content">
    <div class="row">
      <div class="col">
        <form method="post">
          <div class="card my-2">
            <div class="card-body">
              <div class="card-text">
                {% csrf_token %}
                {% form form %}
              </div>
            </div>
          </div>
          <div class="dvzo-buttons-bottom">
            <input type="submit" value="{% translate 'template.rent.submit' %}" class="btn btn-primary btn-sm">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function(){
    const multipleCancelButton = new Choices('#id_renter', {
      removeItemButton: true,
      searchResultLimit:5,
      renderChoiceLimit:5
    });
  });
</script>
{% endblock scripts %}